### ISSUE TITLE
Change the game's window resolution instead of the project's viewport resolution

### ISSUE THREAD

**Issue by Tungill** [Danim3D/Godot-4-Plugin-Project-Resolution#1]
If the goal is to test various resolutions for your game it should change the game's window resolution and not the project's viewport resolution.
The viewport resolution should stay the same during a project because it allows to decide the size needed for the art assets, especially in pixel art games. So it's better if the parameter is only accessible manually. While changing the game's resolution instead would allow to test the responsiveness of the UI and the resolution of the assets on different screen sizes and ratios.

There is a parameter in **Project Settings > Display > Size** which allows to target the resolution of the game's window:
**[Window Width Override](window_width_override)** & **[Window Height Override](window_width_override)**.
In `ProjectResolution.gd` you only have to change for these parameters in `func _set_resolution(id)`
`		ProjectSettings.set_setting("display/window/size/window_width_override", res[0])`
`		ProjectSettings.set_setting("display/window/size/window_height_override", res[1])`

**Comment by Danim3D** [comment]
Thanks for your suggestion. I updated the plugin to instead change the game's window resolution by default. I also added an option to Change Viewport Resolution.
